productName = "gg"
version = "0.29.0"
identifier = "au.gulbanana.gg"

[build]
beforeDevCommand = "bun run dev"
devUrl = "http://localhost:6973"
beforeBuildCommand = "bun run build"
frontendDist = "../dist"

[app]
[[app.windows]]
label = "main"
title = "GG - Gui for JJ"
decorations = true
resizable = true
focus = true
width = 1280
height = 720
visible = false
dragDropEnabled = false

[app.security]
# "csp": null

[bundle]
active = true # Comment this out or set to false to disable bundle compilation
targets = "all"
icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico",
]

[plugins]
