changelog:
  exclude:
    labels:
      - ignore-for-release
      - duplicate
      - invalid
    authors:
      - dependabot[bot]
  categories:
    - title: ✨ new features
      labels:
        - feature
    - title: 🐛 bug fixes
      labels:
        - fix
    - title: 🎨 UI/UX improvements
      labels:
        - ui/ux
    - title: 📝 configuration and documentation
      labels:
        - config
        - docs
    - title: 🔧 refactor and optimization
      labels:
        - refactor
        - optimization
    - title: 📦 dependency management
      labels:
        - deps
        - build
    - title: 🔄 CI/CD updates
      labels:
        - ci/cd
    - title: 🔀 other changes
      labels:
        - "*"
