[vizjj.queries]
# Number of commits to load per call
log-page-size = 1000

# Some query settings will default to false instead of true if a repo has this many commits.
large-repo-heuristic = 100000

# Take a snapshot when the window gains focus; slow in large checkouts.
# When disabled, snapshots will still be created if you run commands.
# auto-snapshot =

[vizjj.ui]
# Stores a list of recently opened directories for shell integration
recent-workspaces = []

# When set, bookmarks that are local-only or remote-only will be visually indicated.
mark-unpushed-bookmarks = true

# todo: "light" or "dark". If not set, default dark.
# theme-override =
