name: "ci"

on:
  push:
    branches:
      - master

jobs:
  svelte-check:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: install packages
        run: bun install --package-lock=false

      - name: run check
        run: bun run check

  cargo-test:
    runs-on: "ubuntu-22.04"
    env:
      RUST_BACKTRACE: "1"
        run: npm install --package-lock=false

      - name: run svelte check
        run: npm run check

      - name: check frontend formatting
        run: npx prettier --check "**/*.{js,ts,svelte,json,css,md,yml}" "!package-lock.json" "!src-tauri/gen/**" "!src/messages/**"

  rust-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
        run: npm install --package-lock=false

      - name: run svelte check
        run: npm run check

      - name: check frontend formatting
        run: npm run fmt

  rust-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v4

      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
          version: 1.0

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "src-tauri"

      - name: run tests
        run: cd src-tauri && cargo test
